# frozen_string_literal: true

require_relative "oscal/address"
require_relative "oscal/address_line"
require_relative "oscal/back_matter"
require_relative "oscal/base64_object"
require_relative "oscal/catalog"
require_relative "oscal/choice"
require_relative "oscal/citation"
require_relative "oscal/component"
require_relative "oscal/constraint"
require_relative "oscal/control"
require_relative "oscal/document_id"
require_relative "oscal/email_address"
require_relative "oscal/external_id"
require_relative "oscal/group"
require_relative "oscal/guideline"
require_relative "oscal/hash_object"
require_relative "oscal/link"
require_relative "oscal/location"
require_relative "oscal/location_uuid"
require_relative "oscal/member_of_organization"
require_relative "oscal/metadata_block"
require_relative "oscal/parameter"
require_relative "oscal/part"
require_relative "oscal/party"
require_relative "oscal/party_uuid"
require_relative "oscal/profile"
require_relative "oscal/property"
require_relative "oscal/prose"
require_relative "oscal/resource"
require_relative "oscal/responsible_party"
require_relative "oscal/revision"
require_relative "oscal/rlink"
require_relative "oscal/role"
require_relative "oscal/select"
require_relative "oscal/serializer"
require_relative "oscal/statement"
require_relative "oscal/telephone_number"
require_relative "oscal/test"
require_relative "oscal/url"
require_relative "oscal/value"
require_relative "oscal/version"

module Oscal
  class Error < StandardError; end

  class UnknownAttributeError < Error; end
  class InvalidTypeError < Error; end
end
